options:
  mode:
    type: string
    default: "http"
    description: "Use of http or tcp for reverseproxy"
  urlbase:
    type: string
    default: ""
    description: "Url for redirect in http mode, must include leading /"
  subdomain:
    type: string
    default: ""
    description: "Subdomain for redirect in http mode"
  group-id:
    type: string
    default: ""
    description: "Optional group id setting from reverseproxy interface"
  external-port:
    type: int
    default: 80
    description: "The external port the provider will listen on"
  internal-port:
    type: int
    default: 80
    description: "The internal port on the host to redirect to"
    
# Example options
#  string-option:
#    type: string
#    default: "Default Value"
#    description: "A short description of the configuration option"
#  boolean-option:
#    type: boolean
#    default: False
#    description: "A short description of the configuration option"
#  int-option:
#    type: int
#    default: 9001
#    description: "A short description of the configuration option"

